config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  get "/products/search", to: "products#search"

  resources :products do
    resources :bookings, only: [:show]
    resources :product_assignments, only: [:new, :create]
  end
  resources :bookings
  resources :product_assignments, only: [:destroy]

  post 'product_assignments', to: 'product_assignments#create'

  get "/products/search", to: "products#search"
  # get "/products/:id/booking/:id", to: "bookings#show_created", as: "booking_created"

  get '/owner/products', to: 'products#index_owner'
  get '/owner/products/:id', to: 'products#show_owner', as: 'owner_product'
  get '/owner/bookings', to: 'bookings#index_owner'
  get '/products/show/:id', to: 'products#show'
  get '/owner/bookings/:id', to: 'bookings#show_owner', as: 'owner_booking'
  patch '/owner/bookings/:id/confirm', to: 'bookings#confirm', as: 'owner_confirm'
  patch '/owner/bookings/:id/decline', to: 'bookings#decline', as: 'owner_decline'
  patch 'bookings/:id/checkout', to: 'bookings#checkout', as: 'checkout'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  has_many :product_assignments, dependent: :destroy
  has_many :products, through: :product_assignments

  validates :start_date, :end_date, :booking_status, presence: true
  validates :end_date, comparison: { greater_than_or_equal_to: :start_date }
  validates :start_date, comparison: { greater_than_or_equal_to: Date.today }

  enum :booking_status, { draft: 0, unconfirmed: 1, confirmed: 2, completed: 3, declined: 4 }, default: :draft

  def booking_days
    ((end_date - start_date) / 86_400).round(0)
  end

  def update_price
    price_per_day = 0
    products.each do |product|
      price_per_day += product.price
    end
    total = price_per_day * booking_days
    update(price: total)
  end
end

app/models/product.rb
class Product < ApplicationRecord
  CATEGORY_NAME = ["mountain bike", "road bike", "hybrid bike", "accessories"]
  PRODUCT_TYPE_NAME = %w[bike helmets shoes locks guards pumps stand straps lights]
  FILE_TYPES = %w[image/jpeg image/png].freeze
  MAX_FILE_SIZE = 10_000_000

  belongs_to :user
  has_many :product_assignments, dependent: :destroy
  has_many :bookings, through: :product_assignments
  has_one_attached :photo, dependent: :destroy

  validates :category, :name, :description, :price, :product_type, presence: true
  validates :category, inclusion: { in: CATEGORY_NAME }
  validates :product_type, inclusion: { in: PRODUCT_TYPE_NAME }

  validate :validate_file_filetypes
  validate :validate_file_filesize

  private

  def validate_file_filetypes
    return unless photo.attached?

    errors.add(:photo, 'must be a JPG or PNG') unless photo.content_type.in?(FILE_TYPES)
  end

  def validate_file_filesize
    return unless photo.attached?

    errors.add(:photo, 'must be max. 10mb') unless photo.blob.byte_size <= MAX_FILE_SIZE
  end
end

app/models/product_assignment.rb
class ProductAssignment < ApplicationRecord
  belongs_to :product
  belongs_to :booking
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # , :timeoutable,  and :omniauthable
  # TO BE ADDED LATER - :confirmable, :trackable
  devise :database_authenticatable, :registerable,
         :recoverable, :validatable, :lockable

  has_many :products, dependent: :destroy
  has_many :bookings, dependent: :destroy

  validates :first_name, :last_name, :zip_code, presence: true
  validates :zip_code, format: { with: /\A\d{5}\z/, message: 'only allows 5 digits' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name zip_code])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name zip_code])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[show confirm decline checkout edit booking_days]

  def index
    # includes loads all the products into memory so you dont have to make alot of sql queries
    @bookings = current_user.bookings.includes(:products)
  end

  def index_owner
    @bookings = current_user.products.map(&:bookings).flatten
  end

  def show
    @product = Product.find(params[:product_id])
  end

  def show_owner
    @booking = Booking.find(params[:id])
    # needs to be refactored with pundit - acces to the booking only possible if
    # owner = owner of product related to booking
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user_id = current_user.id
    @product_assignment_controller = ProductAssignmentsController.new

    @product = Product.find(params[:product_id])
    if @booking.save
      @product_assignment_controller.create_bike(@product, @booking)
      redirect_to product_booking_path(@product, @booking), notice: "Booking has been created"
    else
      render "products/show", status: :unprocessable_entity

    end
  end

  def checkout
    @booking.update(booking_status: "unconfirmed")
    redirect_to product_booking_path(product_id: :product_id, id: :booking_id)
  end


  def confirm
    @booking.update(booking_status: "confirmed")
    redirect_to owner_booking_path
  end

  def decline
    @booking.update(booking_status: "declined")
    redirect_to owner_booking_path
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :booking_status, :product_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/product_assignments_controller.rb
class ProductAssignmentsController < ApplicationController
  before_action :set_product, only: %i[create]
  before_action :set_product_assignment, only: %i[destroy]

  def create
    @product_assignment = ProductAssignment.new(product_assignment_params)
    if @product_assignment.save
      @product_assignment.booking.update_price
      redirect_to product_booking_path(product_id: :product_id, id: :booking_id)
    else
      render 'products/show', alert: 'sth went wrong'
    end
  end

  def create_bike(product, booking)
    @product_assignment = ProductAssignment.new(product: product, booking: booking)
    @product_assignment.save
    booking.update_price
  end

  def destroy
    @product_assignment.destroy
    redirect_to product_booking_path(product_id: :product_id, id: :booking_id)
  end

  private

  def set_product
    @product = Product.find(params[:product_id])
  end

  def set_product_assignment
    @product_assignment = ProductAssignment.find(params[:id])
  end

  def product_assignment_params
    params.permit(:product_id, :booking_id)
  end

  def permit_booking_id
    params.permit(:booking_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index search show]
  before_action :set_product, only: %i[edit update show_owner show destroy]

  def index
    @products = Product.where.not(category: "accessories")
  end

  def search
    if params[:product].nil?
      @products = Product.where.not(category: "accessories")
    else
      @products = Product.where(category: params[:product][:category])
    end
  end

  def index_owner
    @products = Product.where(user: current_user)
  end

  def show_owner
  end

  def show
    @booking = Booking.new
    @product_assignment = ProductAssignment.new
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user

    if @product.save
      redirect_to owner_product_path(@product)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to owner_product_path(@product)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product.destroy
    redirect_to owner_products_path, status: :see_other
  end

  private

  def product_params
    params.require(:product).permit(:category, :name, :description, :price, :photo, :product_type)
  end

  def set_product
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for [booking] do |f| %>
  <%= f.input :start_date, as: :string, input_html: {class: "datepicker"} %>
  <%= f.input :end_date, as: :string, input_html: {class: "datepicker"} %>
  <% if current_user %>
    <%= f.submit nil, { class: "btn btn-primary w-100" } %>
  <% else %>
    <div class="w-100 justify-content-center">
      <%= link_to 'Login to create a booking', new_user_session_path, class: "btn btn-primary" %><br>
      <div class="d-flex align-items-baseline">
        <p>No account yet?</p>
        <%= link_to 'Register now', new_user_registration_path, class: "btn btn-link" %>
      </div>
    </div>
  <% end %>
  <%= hidden_field_tag :product_id, @product.id %>
<% end %>

app/views/bookings/_show_product_booking.html.erb
 <%# Refactoring %>
  <div class="card-product col-7">
    <div class="card rounded-lg p-3 shadow">
      <div class="">
         <% unless product.photo.blank? %>
            <%= cl_image_tag product.photo.key, height: 470, width: 700, crop: :fill, class: "mb-3" %>
          <% else %>
            <img src="https://res.cloudinary.com/drmzvuqzo/image/upload/c_pad,b_auto:predominant,fl_preserve_transparency/v1669322135/development/4-no-image--410x250_dljpif.jpg" class="img-fluid rounded-start mb-3 p-3 mx-auto d-block" alt="..." width="100px">
          <% end %>
      </div>
      <div class="">
        <div class="card-product-infos">
          <div>
            <h2 class="py-2 fw-bold text-center"><%=product.name.upcase%></h2>
            <div class="d-flex justify-content-between py-1">
              <span><%=product.category.capitalize%></span>
              <span>$<%=product.price.round(0)%> per day</span>
            </div>
          </div>
          <p class="pt-2 text-muted"><%=product.description%></p>
        </div>
      </div>

    </div>
  </div>

  <%= render "bookings/show_product_booking_details", product: @product %>

</div>

app/views/bookings/_show_product_booking_details.html.erb
<div class="container rounded">
  <div class="card rounded col-5 p-2 w-100 shadow">
    <div class="d-flex justify-content-between align-items-baseline px-4">
      <h3 class="py-2 fw-bold text-center">Your booking</h3>
      <div class="me-3 text-center pb-2">
        <%= render 'shared/status', booking_status: @booking.booking_status %>
      </div>
    </div>

    <div class="px-4 pt-0  text-muted text-center">
      <p>Dates: <%= @booking.start_date.strftime('%d/%m/%Y') %> - <%= @booking.start_date.strftime('%d/%m/%Y') %></p>
      <p>Total days: <%= @booking.booking_days  %> days</p>
    </div>
    <div class="border-bottom mx-3"></div>
      <div class="px-4 pt-2">
      <p class="text-center">Your Items:</p>
        <ul class="list-group px-1 pb-2">
          <% @booking.product_assignments.each do |product_assignment| %>
                <li id="list-no-margin" class="list-inline-item p-x-2">
                  <div class="d-flex">
                    <div class="flex-grow-1">
                      <p class="mb-0"><%= product_assignment.product.name %></p>
                      <p class="mb-1" style="font-size:12px;"><%= product_assignment.product.category.capitalize %></p>
                    </div>

                    <% unless product_assignment.product.product_type == "bike" %>
                      <p class="mb-0">$<%= product_assignment.product.price.round(0) %></p>
                      <%= link_to product_assignment_path(product_assignment), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
                        <i class="fa-solid fa-trash ms-3"></i>
                      <% end %>
                    <% else %>
                      <p class="mb-0" style="margin-right:30px;">$<%= product_assignment.product.price.round(0) %></p>
                    <% end %>
                  </div>
                </li>
          <% end %>
        </ul>
      </div>
    <div class="border-bottom mx-3"></div>
    <div class="px-4 pt-2 pb-0">
          <div class="d-flex justify-content-between">
            <p>Bike price per day</p>
            <p>$<%= (@product.price).round(0) %></p>
          </div>
        </div>
        <div class="border-bottom mx-3"></div>
        <div class="px-4 pt-2 pb-0">
          <div class="d-flex justify-content-between pt-2 pb-0">
            <p>Total price</p>
            <p>$<%= (@booking.price).round(0) %></p>
          </div>
        </div>
    <% if @booking.booking_status == "draft" %>
      <form method="PATCH" action="<%= checkout_path(@booking) %>", class="p-3">
        <input type="hidden" name="product_id" value="<%= params[:product_id] %>">
        <input type="submit", class="btn btn-primary w-100", value="Checkout">
      </form>
    <% end %>
  </div>
</div>

app/views/bookings/destroy.html.erb
<h1>Bookings#destroy</h1>
<p>Find me in app/views/bookings/destroy.html.erb</p>

app/views/bookings/edit.html.erb
<h1>Bookings#edit</h1>
<p>Find me in app/views/bookings/edit.html.erb</p>

app/views/bookings/index.html.erb
<div class="container p-3">

<h1>These are your bookings</h1>
<% @bookings.each do |booking| %>
  <div class="card my-4 rounded">
    <h5 class="card-header"><%= render "shared/status", booking_status:  booking.booking_status %></h5>
    <div class="card-body">
      <h5 class="card-title"><%= booking.start_date.strftime('%d/%m/%Y') %> - <%= booking.end_date.strftime('%d/%m/%Y') %> </h5>
      <p class="card-text">Items associated with this listing</p>
      <%# item list%>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Category</th>
          </tr>
        </thead>
        <tbody>
        <%# You can call the list of products directly for each booking because of the relationship %>
        <% booking.products.each do | product |%>
          <tr>
            <td><%= product.name.capitalize %></td>
            <td><%= product.category.capitalize %></td>
          </tr>
        <%end%>
        </tbody>
      </table>
      <div class="row">
        <div class="col-2 m-3">Total: $<%=booking.price.round(0)%>
        </div>
      </div>
      <%# Remember with nested paths with params being sent you need to name the params %>
      <%# When its by it self the path will auto asume you are looking for the id of that object %>
      <%# Example home_path(@home) => look for the id of the home even through you are sending over an object %>
      <%= link_to "See Booking", product_booking_path(product_id: booking.products.first.id, id: booking.id), class: "btn btn-primary" %>
    </div>
  </div>
<% end %>
</div>

app/views/bookings/index_owner.html.erb
<div class="d-flex justify-content-between align-items-center mb-3">
  <h1>All your bookings</h1>
</div>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">ID</th>
      <th scope="col">Customer</th>
      <th scope="col">Bike</th>
      <th scope="col">Overall price</th>
      <th scope="col">Status</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @bookings.each_with_index do |booking, index| %>
      <tr>
        <th scope="row"><%= index + 1 %></th>
        <td><%= booking.id %></td>
        <td><%= booking.user.first_name %></td>
        <td><%= link_to booking.products.first.name, owner_product_path(booking.products.first) %></td>
        <td><%= booking.price.round(0) %></td>
        <td><%= render 'shared/status', booking_status: booking.booking_status %></td>
        <td class="d-flex">
          <%= link_to owner_booking_path(booking) do %>
            <i class="fa-regular fa-folder-open me-3"></i>
          <% end %>
          </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/bookings/new.html.erb
<div class="container p-3">
  <h1>Add Product to Booking</h1>

  <%= render "form", { booking: @booking, product: @product } %>
</div>

app/views/bookings/show.html.erb
<div class="container d-flex overflow-hidden rounded p-3">
  <%= render "bookings/show_product_booking", product: @product %>
</div>
  <%= render "products/acc_card", { product: @product, booking: @booking } %>

app/views/bookings/show_owner.html.erb
<div class="d-flex justify-content-between align-items-center mb-3">
  <div class="mb-3">
    <h1>Details on Booking with ID <%= @booking.id %></h1>
    <p ><%= @booking.start_date %> - <%= @booking.end_date %></p>
  </div>
  <div>
    <%= render 'shared/status', booking_status:  @booking.booking_status %>
  </div>
</div>

<div class="row">
<div class="col-12 col-lg-9">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Attribute</th>
          <th scope="col">Detail</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            Start
          </td>
          <td>
            <%=  @booking.start_date %>
          </td>
        </tr>
        <tr>
          <td>
            End
          </td>
          <td>
            <%=  @booking.end_date %>
          </td>
        </tr>
        <tr>
          <td>
            Price
          </td>
          <td>
            <%=  @booking.price.round(0) %>
          </td>
        </tr>
        <tr>
          <td>
            Products
          </td>
          <td>
            <ul>
            <% @booking.products.each do |product| %>
            <li> <%= link_to product.name, owner_product_path(product) %></li>
            <% end %>
            </ul>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="col-12 col-lg-3">
    <form method="PATCH" action="<%= owner_confirm_path(@booking) %>", class=""><input type="submit", class="btn btn-primary w-100 m-2", value="Mark as confirmed"></form>
    <br>
    <form method="PATCH" action="<%= owner_decline_path(@booking) %>", class=""><input type="submit", class="btn btn-primary w-100 m-2", value="Mark as declined"></form>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookAppO</title>
    <%= favicon_link_tag asset_path('logo.svg') %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <% unless notice.nil?%>
      <div class="notice alert alert-success" role="alert">
        <%= notice %> <i class="fa-solid fa-bicycle"></i>
      </div>
    <%end%>
    <% unless alert.nil?%>
      <div class="alert alert-danger" role="alert">
        <%= alert %> <i class="fa-solid fa-bicycle"></i>
      </div>
    <%end%>
      <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
  <div class="container">
    <h1>Rent your bike with BookAppO</h1>
    <p>powered by GroupAppO</p>
    <%= link_to "Find your bike", products_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/product_assignments/_new.html.erb
<form action="<%= product_assignments_path %>", method="POST">
  <input type="hidden" name="product_id" value="<%= product.id %>">
  <input type="hidden" name="booking_id" value="<%= params[:id] %>">
  <input type="submit" name="commit" value="Add to booking" class="btn btn-primary w-100">
</form>

app/views/product_assignments/create.html.erb
<h2>creating</h2>

app/views/products/_form.html.erb
  <%= simple_form_for(product)  do |f| %>
      <%=  f.input :category, collection: Product::CATEGORY_NAME, placeholder: 'Click here to select a category'  %>
      <%=  f.input :product_type, collection: Product::PRODUCT_TYPE_NAME, placeholder: 'Click here to select a product type'  %>
      <%=  f.input :name, placeholder: 'Tyrant by Umbrella Corp.'  %>  %>
      <%=  f.input :description, placeholder: 'The Tyrant virus allegedly operates similarly to most other viruses, but also has the abilities to animate dead tissue, to substantially mutate its host, and to infect nearly any tissue in any type of host. It animates dead tissue by killing...' %>
      <%=  f.input :price, placeholder: '69.0' %>
      <%= f.input :photo, as: :file %>
      <%= f.submit %>
  <% end %>

app/views/products/_index_card.html.erb
<div class="card mb-3 mx-auto p2 me-3 shadow-sm rounded" style="max-width: 600px; height:250px" data-category="<%= product.category %>">
  <div class="row g-0 overflow-hidden m-2" >
    <div class="col-md-6">
      <% unless product.photo.blank? %>
        <%= cl_image_tag product.photo.key, height: 175, width: 280, crop: :fill, class: "mb-3" %>
      <% else %>
        <img src="https://res.cloudinary.com/drmzvuqzo/image/upload/c_pad,b_auto:predominant,fl_preserve_transparency/v1669322135/development/4-no-image--410x250_dljpif.jpg" class="img-fluid rounded-start mb-3" alt="...">
      <% end %>

      <%= link_to "View Product Details", product, { class: "btn btn-primary" } %>
    </div>
    <div class="col-md-6">
      <div class="card-body overflow-hidden">
        <h5 class="card-title"><%=product.name%></h5>
        <p class="card-text"><small class="text-muted"><%=product.category.capitalize%></small></p>
          <div class="row g-0 overflow-hidden text-end pe-3" >
            <h3>$<%=product.price.round(0)%></h3><p> per day</p>

          </div>
      </div>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<div class="row justify-content-center">
  <div class="col-4">
    <h2 class="mt-3">Edit @product.name</h2>
    <%= render 'form', product: @product %>
  </div>
</div>

app/views/products/index_owner.html.erb
<div class="d-flex justify-content-between align-items-center mb-3">
  <h1>All your products</h1>
  <%= link_to "Add product", new_product_path, class: "btn btn-primary" %>
</div>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">ID</th>
      <th scope="col">Category</th>
      <th scope="col">Product type</th>
      <th scope="col">Name</th>
      <th scope="col">Price</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each_with_index do |product, index| %>
      <tr>
        <th scope="row"><%= index + 1 %></th>
        <td><%= product.id %></td>
        <td><%= product.category %></td>
        <td><%= product.product_type %></td>
        <td><%= product.name %></td>
        <td>$<%= product.price.round(0) %></td>
        <td class="d-flex">
          <%= link_to owner_product_path(product) do %>
            <i class="fa-regular fa-folder-open me-3"></i>
          <% end %>
          <%= link_to edit_product_path(product) do %>
            <i class="fa-solid fa-pen-to-square me-3"></i>
          <% end %>
          <%= link_to product_path(product), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
            <i class="fa-solid fa-trash-can"></i>
          <% end %>
          </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<div class="row justify-content-center">
  <div class="col-4">
    <h2 class="mt-3">Create new product</h2>
    <%= render 'form', product: @product %>
  </div>
</div>

app/views/products/search.html.erb
<%= simple_form_for :product, url: products_search_path, method: :get, html: { class: 'form-inline' } do |f| %>
  <%= f.input :category, collection: Product::CATEGORY_NAME, label: false, placeholder: "mountain bike", include_blank: false, include_hidden: false %>
  <%= f.submit "Search", class: "btn btn-primary" %>
<% end %>


<% @products.each do |product| %>
    <%= render "index_card", product: product %>
<%end%>

app/views/products/show_owner.html.erb
<div class="justify-content-between align-items-center mb-3">
  <h1>Details on <%= @product.name %></h1>
  <p>Last updated on <%=  @product.updated_at.to_fs(:long)  %></p>
</div>

<div class="row">
<div class="col-12 col-lg-9">
    <table class="table">
      <thead>
        <tr>
            <th scope="col">Attribute</th>
            <th scope="col">Detail</th>
          </tr>
        </thead>
        <tbody>
          <tr>
          <td>
            Picture
          </td>
          <td>
            <%= cl_image_tag @product.photo.key, height: 300, width: 400, crop: :fill %>
          </td>
          <tr>
          <td>
            Category
          </td>
          <td>
            <%=  @product.category %>
          </td>
        </tr>
        <tr>
          <td>
            Product type
          </td>
          <td>
            <%=  @product.product_type %>
          </td>
        </tr>
        <tr>
          <td>
            Name
          </td>
          <td>
            <%=  @product.name %>
          </td>
        </tr>
        <tr>
          <td>
            Description
          </td>
          <td>
            <%=  @product.description %>
          </td>
        </tr>
        <tr>
          <td>
            Price per Day
          </td>
          <td>
            <%=  @product.price.round(0)    %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
<div class="col-12 col-lg-3">
    <%= link_to "Edit product", edit_product_path(@product), class: "btn btn-primary w-100 m-2" %>
    <br>
    <%= link_to "Delete product", product_path(@product), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-primary w-100 m-2"   %>
</div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid container pb-1 border-bottom">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.svg", style: 'height:30px;width:auto;' %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto flex-grow-1">
        <%# Menu %>
          <li class="nav-item">
            <%= link_to "See all products", products_path, class: "nav-link" %>
          </li>
          <% if user_signed_in? %>

          <li class="nav-item">
            <%= link_to "See all bookings", bookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDarkDropdown" aria-controls="navbarNavDarkDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
            <ul class="navbar-nav">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Owner Directory
                </a>
                <ul class="dropdown-menu dropdown-menu-light" aria-labelledby="navbarDarkDropdownMenuLink">
                  <li><%= link_to "My products", owner_products_path, class: "dropdown-item" %></li>
                  <li><%= link_to "My bookings", owner_bookings_path, class: "dropdown-item" %></li>
                </ul>
              </li>
            </ul>
          </div>
          </li>



          </ul>
          <ul class="navbar-nav me-auto">
            <li class="nav-item dropdown">
              <%= link_to "Log out", destroy_user_session_path, class: "btn btn-primary", data: {turbo_method: :delete} %>
              </div>
            </li>

          <% else %>
        </ul>
        <%# login buton %>
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "btn btn-primary" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>